<?php
$topics = $this->topics;
foreach ($topics as $topic) {
    ?>
    <section>
        <div class="row">
            <div class="col-xs-12">
                <h3><?=$topic['title'];?></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <p class="text-muted">
                    <?=nl2br($topic['description']);?>
                </p>
            </div>
            <div class="col-xs-4">
                <p class="pull-right">
                    <a href="/edit?id=<?=$topic['id']; ?>" class="btn btn-primary">Edit</a>
                    <a href="/delete?id=<?=$topic['id']; ?>" class="btn btn-danger" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Are you sure?" data-content=" This cannot be undone!">Delete</a>
                </p>
            </div>
        </div>
    </section>
    <hr>
    <?php
}
?>